/**
 * Tier-1 offline unit tests for the deterministic payload generator and the
 * single-`blob`-field fixture schemas.
 *
 * Two properties matter for cross-language benchmark honesty and are pinned
 * here so drift fails the build:
 *
 *   1. **Byte-identity with the reference generator.** The Go reference
 *      ships an xorshift64 generator with a fixed seed and a fixed 64-char
 *      alphabet. If the TypeScript implementation drifts by a single bit,
 *      the MB/s columns in the comparison report stop being apples-to-apples
 *      because the two sides are consuming different bytes. The SHA-256 hex
 *      digests below are the falsifiable pin: each was computed against the
 *      exact same algorithm+seed+alphabet as the Go reference, and any
 *      change to `perfPayload` that reshapes its bytes will flip the digest.
 *
 *   2. **Determinism within a run and across runs.** Two successive calls to
 *      `perfPayload(size)` for the same size must return byte-identical
 *      buffers (the seed is fixed and the algorithm holds no external
 *      state). Benchstat-style regression detection depends on the input
 *      being stable, so this property is asserted in addition to the
 *      digest pin.
 *
 * These tests are pure in-process: no network, no filesystem I/O beyond
 * module resolution, no Docker, no JVM. They are collected by the default
 * `vitest run` invocation via the bench-directory unit-test include glob.
 */

import { createHash } from "node:crypto";

import { describe, expect, it } from "vitest";

import {
  PERF_AVRO_SCHEMA,
  PERF_JSON_SCHEMA,
  PERF_PAYLOAD_ALPHABET,
  PERF_PAYLOAD_MESSAGE_FULL_NAME,
  PERF_PAYLOAD_SEED,
  PERF_PROTO_TEXT_SCHEMA,
  perfPayload,
} from "./payloads.js";

/**
 * Pinned SHA-256 hex digests for `perfPayload(size)` at the three benchmark
 * sizes. Computed against the same xorshift64+alphabet+seed as the Go
 * reference — see the module-level comment on `payloads.ts` for the tie
 * to the Go source.
 *
 * A hex digest is used deliberately rather than a literal payload prefix:
 * a raw payload substring lives in the 64-char printable alphabet
 * (letters, digits, space, ".") which could — for a specific size — start
 * with a sequence a human might read as a planning label, and a hex
 * digest cannot. Hex characters `[0-9a-f]` are structurally disjoint from
 * every alphabetic identifier the committed-file grep flags.
 */
const PINNED_DIGESTS: ReadonlyArray<readonly [number, string]> = [
  [100, "8f75995a7e4fdde56c670989ee32d8173e654c38527557d3098626aec11dbbac"],
  [10240, "6e9ce2f6a9c60856ba1e14229620de1b2e80316143683c7137172c7c1682523f"],
  [1048576, "b97384cebe956b198e9b17ba531dff02744e16903d795d6d94c6896524835fe3"],
];

function sha256Hex(buf: Buffer): string {
  return createHash("sha256").update(buf).digest("hex");
}

describe("perfPayload — deterministic xorshift64 generator", () => {
  it("returns an empty buffer for size <= 0", () => {
    expect(perfPayload(0).length).toBe(0);
    expect(perfPayload(-1).length).toBe(0);
  });

  it("throws TypeError on a non-integer size", () => {
    expect(() => perfPayload(1.5)).toThrow(TypeError);
    expect(() => perfPayload(Number.NaN)).toThrow(TypeError);
  });

  it("returns a buffer of the requested length for each pinned size", () => {
    for (const [size] of PINNED_DIGESTS) {
      const p = perfPayload(size);
      expect(p.length, `perfPayload(${size}).length`).toBe(size);
    }
  });

  it("emits bytes byte-identical to the reference xorshift64 generator (SHA-256 pin)", () => {
    for (const [size, expected] of PINNED_DIGESTS) {
      const digest = sha256Hex(perfPayload(size));
      expect(digest, `SHA-256 digest for perfPayload(${size})`).toBe(expected);
    }
  });

  it("emits only characters from the 64-char alphabet (printable ASCII)", () => {
    // Every generated byte must fall in the alphabet — this is what lets the
    // payload round-trip losslessly as a JSON `string` field and as a
    // protobuf `string blob` field. Sample a bounded prefix so the assertion
    // is O(1) in test cost independent of the full 1 MB size.
    const p = perfPayload(4096);
    const alphabet = new Set(PERF_PAYLOAD_ALPHABET);
    for (let i = 0; i < p.length; i++) {
      const ch = String.fromCharCode(p[i]!);
      expect(alphabet.has(ch), `byte at index ${i} (0x${p[i]!.toString(16)}) must be in alphabet`).toBe(true);
    }
  });

  it("is deterministic across successive calls", () => {
    // Two successive calls at the same size must produce byte-identical
    // output — the generator holds no external state and the seed is fixed.
    for (const size of [100, 10240]) {
      const a = perfPayload(size);
      const b = perfPayload(size);
      expect(a.equals(b), `perfPayload(${size}) must be byte-identical across calls`).toBe(true);
    }
  });

  it("prefix of a larger payload equals a smaller payload (streaming property)", () => {
    // The xorshift64 algorithm has no length-dependent branching, so the
    // first N bytes of `perfPayload(N + k)` must equal `perfPayload(N)`.
    // This catches a regression where a length-aware finalizer step
    // silently reshapes the tail bytes at some sizes.
    const short = perfPayload(1024);
    const long = perfPayload(10240);
    expect(long.subarray(0, 1024).equals(short)).toBe(true);
  });
});

describe("fixture-schema constants", () => {
  it("exposes the pinned xorshift64 seed as a BigInt", () => {
    expect(typeof PERF_PAYLOAD_SEED).toBe("bigint");
    expect(PERF_PAYLOAD_SEED).toBe(0x9e3779b97f4a7c15n);
  });

  it("exposes a 64-character alphabet", () => {
    expect(PERF_PAYLOAD_ALPHABET.length).toBe(64);
    // The alphabet must be composed only of printable-ASCII bytes.
    for (let i = 0; i < PERF_PAYLOAD_ALPHABET.length; i++) {
      const code = PERF_PAYLOAD_ALPHABET.charCodeAt(i);
      expect(code, `char code at ${i}`).toBeGreaterThanOrEqual(0x20);
      expect(code, `char code at ${i}`).toBeLessThan(0x7f);
    }
  });

  it("exposes the fully-qualified protobuf message name", () => {
    expect(PERF_PAYLOAD_MESSAGE_FULL_NAME).toBe("perf.Payload");
  });

  it("Avro schema is valid JSON with the expected single `blob` string field", () => {
    const parsed = JSON.parse(PERF_AVRO_SCHEMA) as {
      type: string;
      name: string;
      namespace: string;
      fields: Array<{ name: string; type: string }>;
    };
    expect(parsed.type).toBe("record");
    expect(parsed.name).toBe("PerfRecord");
    expect(parsed.namespace).toBe("perf");
    expect(parsed.fields).toHaveLength(1);
    expect(parsed.fields[0]!.name).toBe("blob");
    expect(parsed.fields[0]!.type).toBe("string");
  });

  it("JSON-Schema is valid JSON with the expected single `blob` string property", () => {
    const parsed = JSON.parse(PERF_JSON_SCHEMA) as {
      type: string;
      properties: Record<string, { type: string }>;
      required: string[];
    };
    expect(parsed.type).toBe("object");
    expect(parsed.properties.blob!.type).toBe("string");
    expect(parsed.required).toEqual(["blob"]);
  });

  it("proto text schema declares proto3 package `perf` with message `Payload { string blob = 1 }`", () => {
    expect(PERF_PROTO_TEXT_SCHEMA).toContain('syntax = "proto3"');
    expect(PERF_PROTO_TEXT_SCHEMA).toContain("package perf;");
    expect(PERF_PROTO_TEXT_SCHEMA).toContain("message Payload");
    expect(PERF_PROTO_TEXT_SCHEMA).toContain("string blob = 1");
  });
});
